# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '3rdWheelTestDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 3rdWheelTestDemo

  target '3rdWheelTestDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '3rdWheelTestDemoUITests' do
    # Pods for testing
  end

end
