# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target '3rdWheelTestDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 3rdWheelTestDemo
  
  pod 'SSZipArchive'                   # zip解压
  pod 'AFNetworking'                   # 网络请求
  pod 'lottie-ios', '~> 2.5.2'         # 动画

  target '3rdWheelTestDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '3rdWheelTestDemoUITests' do
    # Pods for testing
  end

end
